### ISSUE TITLE
The reason why this project is stopped

### ISSUE THREAD

**Issue by ChuyuHsu** [zhangzibin/deep-skip-thoughts#2]
With my respect,
what do you mean "This project is stopped because the model is a little out-of-date in research area about sequence-to-sequence."?
If there exists better model, could you kindly guide me there?

**Comment by zhangzibin** [comment]
@ChuyuHsu  Sequence-to-sequence models with attention are much better as reported in many papers. Refer to Bengio's talk recently [Twitter-11May2016.pdf](https://dl.dropboxusercontent.com/u/19557502/Twitter-11May2016.pdf).

In my opinion, sequence generation using dynamic context (eg. attention on hidden states) is much better than using global context. But skip-thoughts is useful if you need sentence-to-vector, which is a bit slow for better performance.
